client_index:
    path:     /
    defaults: { _controller: "GestionBundle:Client:index" }
    methods:  GET
    

client_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Client:show" }
    methods:  GET

client_email:
    path:     /{id}/email
    defaults: { _controller: "GestionBundle:Client:sendEmail" }
    methods:  [GET, POST]

client_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Client:new" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Client:delete" }
    methods:  DELETE
