projet_index:
    path:     /
    defaults: { _controller: "GestionBundle:Projet:index" }
    methods:  GET

projet_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Projet:show" }
    methods:  GET

projet_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Projet:new" }
    methods:  [GET, POST]
    
projet_create:
    pattern:  /create
    defaults: { _controller: "GestionBundle:Projet:create" }
    requirements: { _method: post }

projet_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Projet:edit" }
    methods:  [GET, POST]

projet_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Projet:delete" }
    methods:  DELETE
