tache_index:
    path:     /{id}/index
    defaults: { _controller: "GestionBundle:Tache:index" }
    methods:  GET

tache_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Tache:show" }
    methods:  GET

tache_new:
    path:     /new/{id}
    defaults: { _controller: "GestionBundle:Tache:new" }
    methods:  [GET, POST]

tache_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Tache:edit" }
    methods:  [GET, POST]

tache_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Tache:delete" }
    methods:  DELETE
