<?php

namespace Proxies\__CG__\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \GestionBundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'dateDebut', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'dateFin', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'cout', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'statut', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'adresse', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'taches', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'client', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'personnels');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'dateDebut', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'dateFin', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'cout', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'statut', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'adresse', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'taches', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'client', '' . "\0" . 'GestionBundle\\Entity\\Projet' . "\0" . 'personnels');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', array($dateDebut));

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', array());

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', array($dateFin));

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', array());

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCout($cout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCout', array($cout));

        return parent::setCout($cout);
    }

    /**
     * {@inheritDoc}
     */
    public function getCout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCout', array());

        return parent::getCout();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function addTach(\GestionBundle\Entity\Tache $tach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTach', array($tach));

        return parent::addTach($tach);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTach(\GestionBundle\Entity\Tache $tach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTach', array($tach));

        return parent::removeTach($tach);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaches()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaches', array());

        return parent::getTaches();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\GestionBundle\Entity\User $client = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonnel(\GestionBundle\Entity\User $personnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonnel', array($personnel));

        return parent::addPersonnel($personnel);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonnel(\GestionBundle\Entity\User $personnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonnel', array($personnel));

        return parent::removePersonnel($personnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonnels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonnels', array());

        return parent::getPersonnels();
    }

}
