<?php

namespace Proxies\__CG__\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tache extends \GestionBundle\Entity\Tache implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'dateDebut', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'dateFin', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'duree', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'cout', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'statut', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'progress', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'projet', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'materiels', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'personnels');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'dateDebut', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'dateFin', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'duree', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'cout', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'statut', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'progress', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'projet', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'materiels', '' . "\0" . 'GestionBundle\\Entity\\Tache' . "\0" . 'personnels');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tache $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', array($dateDebut));

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', array());

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', array($dateFin));

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', array());

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', array($duree));

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', array());

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setCout($cout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCout', array($cout));

        return parent::setCout($cout);
    }

    /**
     * {@inheritDoc}
     */
    public function getCout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCout', array());

        return parent::getCout();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgress($progress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgress', array($progress));

        return parent::setProgress($progress);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgress', array());

        return parent::getProgress();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjet(\GestionBundle\Entity\Projet $projet = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjet', array($projet));

        return parent::setProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjet', array());

        return parent::getProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function addMateriels(\GestionBundle\Entity\Materiel $materiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMateriels', array($materiel));

        return parent::addMateriels($materiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMateriels(\GestionBundle\Entity\Materiel $materiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMateriels', array($materiel));

        return parent::removeMateriels($materiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriels', array());

        return parent::getMateriels();
    }

    /**
     * {@inheritDoc}
     */
    public function addMateriel(\GestionBundle\Entity\Materiel $materiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMateriel', array($materiel));

        return parent::addMateriel($materiel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMateriel(\GestionBundle\Entity\Materiel $materiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMateriel', array($materiel));

        return parent::removeMateriel($materiel);
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonnel(\GestionBundle\Entity\User $personnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonnel', array($personnel));

        return parent::addPersonnel($personnel);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonnel(\GestionBundle\Entity\User $personnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonnel', array($personnel));

        return parent::removePersonnel($personnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonnels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonnels', array());

        return parent::getPersonnels();
    }

}
